### ISSUE TITLE
ambari 2.2集成hue 3.11失败

### ISSUE THREAD

**Issue by handsomezp** [EsharEditor/ambari-hue-service#10]
你好，我在ambari 2.2上面集成hue 3.11时在"Assign Masters"步骤报错，截图如下：
![default](https://cloud.githubusercontent.com/assets/24541684/21133763/885bf450-c155-11e6-98ec-97bf0de007e6.jpg)

后台ambari-server日志报错如下：
13 十二月 2016 16:59:04,491  WARN [qtp-ambari-client-167] ServletHandler:563 - /api/v1/stacks/HDP/versions/2.4/recommendations
java.lang.NullPointerException
	at org.apache.ambari.server.state.PropertyInfo.getAttributesMap(PropertyInfo.java:145)
	at org.apache.ambari.server.state.PropertyInfo.convertToResponse(PropertyInfo.java:128)
	at org.apache.ambari.server.controller.AmbariManagementControllerImpl.getStackConfigurations(AmbariManagementControllerImpl.java:3898)
	at org.apache.ambari.server.controller.AmbariManagementControllerImpl.getStackConfigurations(AmbariManagementControllerImpl.java:3867)
	at org.apache.ambari.server.controller.internal.StackConfigurationResourceProvider$1.invoke(StackConfigurationResourceProvider.java:114)
	at org.apache.ambari.server.controller.internal.StackConfigurationResourceProvider$1.invoke(StackConfigurationResourceProvider.java:111)
	at org.apache.ambari.server.controller.internal.AbstractResourceProvider.getResources(AbstractResourceProvider.java:302)
	at org.apache.ambari.server.controller.internal.StackConfigurationResourceProvider.getResources(StackConfigurationResourceProvider.java:111)
	at org.apache.ambari.server.controller.internal.ClusterControllerImpl$ExtendedResourceProviderWrapper.queryForResources(ClusterControllerImpl.java:945)
	at org.apache.ambari.server.controller.internal.ClusterControllerImpl.getResources(ClusterControllerImpl.java:132)
	at org.apache.ambari.server.api.query.QueryImpl.doQuery(QueryImpl.java:508)
	at org.apache.ambari.server.api.query.QueryImpl.queryForSubResources(QueryImpl.java:463)
	at org.apache.ambari.server.api.query.QueryImpl.queryForSubResources(QueryImpl.java:482)
	at org.apache.ambari.server.api.query.QueryImpl.queryForResources(QueryImpl.java:436)
	at org.apache.ambari.server.api.query.QueryImpl.execute(QueryImpl.java:216)
	at org.apache.ambari.server.api.handlers.ReadHandler.handleRequest(ReadHandler.java:68)
	at org.apache.ambari.server.api.services.BaseRequest.process(BaseRequest.java:135)
	at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:106)
	at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:75)
	at org.apache.ambari.server.api.services.stackadvisor.commands.StackAdvisorCommand.getServicesInformation(StackAdvisorCommand.java:356)
	at org.apache.ambari.server.api.services.stackadvisor.commands.StackAdvisorCommand.invoke(StackAdvisorCommand.java:247)
	at org.apache.ambari.server.api.services.stackadvisor.StackAdvisorHelper.recommend(StackAdvisorHelper.java:109)
	at org.apache.ambari.server.controller.internal.RecommendationResourceProvider.createResources(RecommendationResourceProvider.java:92)
	at org.apache.ambari.server.controller.internal.ClusterControllerImpl.createResources(ClusterControllerImpl.java:289)
	at org.apache.ambari.server.api.services.persistence.PersistenceManagerImpl.create(PersistenceManagerImpl.java:76)
	at org.apache.ambari.server.api.handlers.CreateHandler.persist(CreateHandler.java:36)
	at org.apache.ambari.server.api.handlers.BaseManagementHandler.handleRequest(BaseManagementHandler.java:72)
	at org.apache.ambari.server.api.services.BaseRequest.process(BaseRequest.java:135)
	at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:106)
	at org.apache.ambari.server.api.services.BaseService.handleRequest(BaseService.java:75)
	at org.apache.ambari.server.api.services.RecommendationService.getRecommendation(RecommendationService.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.apache.ambari.server.security.authorization.AmbariAuthorizationFilter.doFilter(AmbariAuthorizationFilter.java:196)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.apache.ambari.server.api.MethodOverrideFilter.doFilter(MethodOverrideFilter.java:72)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.apache.ambari.server.api.AmbariPersistFilter.doFilter(AmbariPersistFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.apache.ambari.server.security.AbstractSecurityHeaderFilter.doFilter(AbstractSecurityHeaderFilter.java:109)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:294)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.ambari.server.controller.AmbariHandlerList.processHandlers(AmbariHandlerList.java:216)
	at org.apache.ambari.server.controller.AmbariHandlerList.processHandlers(AmbariHandlerList.java:205)
	at org.apache.ambari.server.controller.AmbariHandlerList.handle(AmbariHandlerList.java:139)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
麻烦帮忙分析下错误原因，谢谢

**Comment by EsharEditor** [comment]
我能先确认下你在ambari 2.2用的ambari-hue-service是那个版本吗？

**Comment by handsomezp** [comment]
我用的是：ambari-hue-service-branch-2.0.0.zip这个版本，谢谢！

**Comment by EsharEditor** [comment]
你好！Ambari-hue-service 2.0.0版本支持Ambari 2.4.0及以上版本，在Ambari 2.2版本不支持。Ambari 2.2只支持ambari-hue-service 1.0.0版本。这个版本问题在README文档里有提到过。所以你在Ambari上安装ambari-hue-service 2.0.0会报你提出的这个错误。

**Comment by handsomezp** [comment]
好的，谢谢，那请问下你会不会针对这个问题进行优化呢？因为ambari-hue-service 1.0.0支持的hue版本较低，我相信很多开发人员或者用户也有这个困惑，谢谢！

**Comment by EsharEditor** [comment]
不好意思，这个问题暂时还不打算进行改进，主要涉及到的一个问题是Ambari 2.2上spark服务未集成Livy Server，Hue 3.9带有Livy Server，而Hue 3.10以上版本已经将这个Livy Server删除，所以当初版本选择上只支持了Hue 3.9版本，否则可能需要单独去部署一个Livy Server。最新的Ambari 2.4及以上版本中Spark服务集成了Livy Server，对于Hue的部署、配置更加方便操作，现在主要优化方向可能都在ambari-hue-service 2.0版本。

**Comment by handsomezp** [comment]
好的，感谢。明白了哈
