### ISSUE TITLE
hue server install  failed！

### ISSUE THREAD

**Issue by 15081306** [EsharEditor/ambari-hue-service#15]
Installation problem
centos7 + hdp 2.5 +ambari Version 2.4.2.0 

hue server install  failed！

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 16, in install
    self.install_packages(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 567, in install_packages
    retry_count=agent_stack_retry_count)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 54, in action_install
    self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/yumrpm.py", line 51, in install_package
    self.checked_call_with_retries(cmd, sudo=True, logoutput=self.get_logoutput())
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 86, in checked_call_with_retries
    return self._call_with_retries(cmd, is_checked=True, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 98, in _call_with_retries
    code, out = func(cmd, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-simplejs

**Comment by EsharEditor** [comment]
Hi:
The problem is that the 'python-simplejson' can not be installed,please confirm whether there is a 'python-simplejson' in yum source.

**Comment by 15081306** [comment]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 18, in install
    download_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/common.py", line 57, in download_hue
    Execute('{0} | xargs wget -O hue.tgz'.format(params.download_url))
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 273, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'cat /etc/yum.repos.d/HDP.repo | grep "baseurl" | awk -F '=' '{print $2"hue/hue-3.11.0.tgz"}' | xargs wget -O hue.tgz' returned 123. --2017-03-23 11:28:08--  http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.5.3.0hue/hue-3.11.0.tgz
Resolving public-repo-1.hortonworks.com (public-repo-1.hortonworks.com)... 54.230.151.100, 54.230.151.4, 54.230.151.42, ...
Connecting to public-repo-1.hortonworks.com (public-repo-1.hortonworks.com)|54.230.151.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-23 11:28:09 ERROR 404: Not Found.
thanks

**Comment by 15081306** [comment]
/etc/yum.repos.d
HDP.repo
baseurl=http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.5.3.0

**Comment by EsharEditor** [comment]
Hi:
  There is no the Hue install-package in the original repository.If you want to install the Hue successful, you need to modify the code with download_url in the params.py file.

**Comment by hm631379593** [comment]
Consistency Check Failed 
The configuration changes could not be validated for consistency due to an unknown error. Your changes have not been saved yet. Would you like to proceed and save the changes? 
 
my version is centos7 + hdp 2.5 +ambari Version 2.4.2.0   how can i solve this problem? thakns

**Comment by MichalMichalak** [comment]
Could you, please, explain more about python-simplejson package? How can one properly get this package installed? Example: on CentOS 7.3 this package does not exist in default repo. There are some similar packages in EPEL repo but designated for specific Python version. My Python is 2.7 so, theoretically, I could install `python2-simplejson` instead but I have no idea is this the same package with different name or something completely different with different API.

```
$ sudo yum search simplejson

python2-simplejson.x86_64 : Simple, fast, extensible JSON encoder/decoder for Python2
python34-simplejson.x86_64 : Simple, fast, extensible JSON encoder/decoder for Python3
```

**Comment by EsharEditor** [comment]
Hi MichalMichalak:
If you compile the hue on Centos7 with python2-simplejson,you can use python2-simplejson.And you need to modify **<package><name>python-simplejson</name></package>** in metainfo.xml before you install hue.

**Comment by MichalMichalak** [comment]
Great. This is what I did, thank you.
