### ISSUE TITLE
start hue server error

### ISSUE THREAD

**Issue by qianmoQ** [EsharEditor/ambari-hue-service#17]
`
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/setup_hue.py", line 27, in setup_hue
    Link("{0}/desktop/libs/hadoop/java-lib/*".format(params.hue_dir),to = "/usr/hdp/current/hadoop-client/lib")
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 238, in action_create
    sudo.symlink(self.resource.to, path)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 93, in symlink
    os.symlink(source, link_name)
OSError: [Errno 2] No such file or directory`

**Comment by AlexanderMok** [comment]
Creating symlinks /usr/hdp/current/hadoop-client/lib/hue-plugins-3.12.0-SNAPSHOT.jar
**Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*']** {'to': '**/usr/hdp/current/hadoop-client/lib**'}
**Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*']** replacing old symlink to /usr/hdp/2.5.3.0-37/hadoop/lib
Creating symbolic **Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*']** to **/usr/hdp/current/hadoop-client/lib**

Here's what I got. Make sure the directory exists.

**Comment by AlexanderMok** [comment]
```
/usr/lib/python2.6/site-packages/resource_management/core/environment.py:165: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  Logger.info("Skipping failure of {0} due to ignore_failures. Failure reason: {1}".format(resource, ex.message))
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/setup_hue.py", line 45, in setup_hue
    owner = params.hue_user
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 138, in action_create
    sudo.create_file(path, content, encoding=self.resource.encoding)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 111, in create_file
    fp.write(content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 3462: ordinal not in range(128)
```

**Here's my problem**. The checking needs to write file `pseudo-distributed.ini`. But the encoding is not right. I do know where to set the encoding.....

```
Writing File['/usr/local/hue/desktop/conf/pseudo-distributed.ini'] because contents don't match
```

**Comment by EsharEditor** [comment]
Hi：
I thinks you should set the enxoding for the sudo.py.

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by NGBALAJI** [comment]
**I have set up the encoding for sudo.py. But still I'm facing the same problem at different line number.
Below is the stderr:**

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 314, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 117, in locking_configure
    original_configure(obj, *args, **kw)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/setup_hue.py", line 27, in setup_hue
    Link("{0}/desktop/libs/hadoop/java-lib/*".format(params.hue_dir),to = "/usr/hdp/current/hadoop-client/lib")
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 238, in action_create
    sudo.symlink(self.resource.to, path)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 96, in symlink
    os.symlink(source, link_name)
OSError: [Errno 2] No such file or directory

**Comment by EsharEditor** [comment]
Does this directory(/usr/hdp/current/hadoop-client/lib) exist?

**Comment by NGBALAJI** [comment]
Yeah, It is there.

**Comment by NGBALAJI** [comment]
Below is the screen shot of ls -ltr /usr/hdp/current/hadoop-client/lib

![capture](https://user-images.githubusercontent.com/24694338/28151103-3fbf45dc-67b6-11e7-8c68-89626cb6a549.PNG)

**Comment by EsharEditor** [comment]
Does this directory(/usr/local/hue/desktop/libs/hadoop/java-lib) exist?
![image](https://user-images.githubusercontent.com/20943153/28154843-6789a918-67de-11e7-8ddf-18683fcafe2a.png)

**Comment by NGBALAJI** [comment]
Not there.
Under (/usr/local/hue/) directory there are continuous hue sub directories.

![image](https://user-images.githubusercontent.com/24694338/28166471-a69c6408-67f5-11e7-96d9-ada6543fbaa1.png)
