### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by hm631379593** [EsharEditor/ambari-hue-service#19]
centos7 + hdp 2.5 +ambari Version 2.4.2.0
waring:
Consistency Check Failed 
The configuration changes could not be validated for consistency due to an unknown error. Your changes have not been saved yet. Would you like to proceed and save the changes? 

how can i slove it ? thanks

**Comment by EsharEditor** [comment]
Hi:
I have the same waring, but there is no influence to install HUE. Are there any problems with installation?

**Comment by hm631379593** [comment]
Wrong the installing fue server.Error is as fellow:
  stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 16, in install
    self.install_packages(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 567, in install_packages
    retry_count=agent_stack_retry_count)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 54, in action_install
    self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/yumrpm.py", line 51, in install_package
    self.checked_call_with_retries(cmd, sudo=True, logoutput=self.get_logoutput())
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 86, in checked_call_with_retries
    return self._call_with_retries(cmd, is_checked=True, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 98, in _call_with_retries
    code, out = func(cmd, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-simplejson' returned 1. Error: Nothing to do
 stdout:
2017-05-19 16:48:09,054 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.0.0-1245
2017-05-19 16:48:09,055 - Checking if need to create versioned conf dir /etc/hadoop/2.5.0.0-1245/0
2017-05-19 16:48:09,056 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-05-19 16:48:09,071 - call returned (1, '/etc/hadoop/2.5.0.0-1245/0 exist already', '')
2017-05-19 16:48:09,072 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-05-19 16:48:09,089 - checked_call returned (0, '')
2017-05-19 16:48:09,089 - Ensuring that hadoop has the correct symlink structure
2017-05-19 16:48:09,089 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-05-19 16:48:09,090 - Group['hue'] {}
2017-05-19 16:48:09,091 - Group['hadoop'] {}
2017-05-19 16:48:09,091 - Group['users'] {}
2017-05-19 16:48:09,091 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,091 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,092 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-05-19 16:48:09,092 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-05-19 16:48:09,092 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,093 - User['hue'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,093 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,093 - User['hcat'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,094 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-19 16:48:09,094 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-05-19 16:48:09,095 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-05-19 16:48:09,100 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-05-19 16:48:09,100 - Group['hdfs'] {}
2017-05-19 16:48:09,100 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': [u'hadoop', u'hdfs']}
2017-05-19 16:48:09,100 - FS Type: 
2017-05-19 16:48:09,101 - Directory['/etc/hadoop'] {'mode': 0755}
2017-05-19 16:48:09,109 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-05-19 16:48:09,109 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-05-19 16:48:09,118 - Initializing 2 repositories
2017-05-19 16:48:09,118 - Repository['HDP-2.5'] {'base_url': 'http://repo.cloud.sinocbd.com/hdp/centos7/', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'HDP', 'mirror_list': None}
2017-05-19 16:48:09,123 - File['/etc/yum.repos.d/HDP.repo'] {'content': '[HDP-2.5]\nname=HDP-2.5\nbaseurl=http://repo.cloud.sinocbd.com/hdp/centos7/\n\npath=/\nenabled=1\ngpgcheck=0'}
2017-05-19 16:48:09,123 - Repository['HDP-UTILS-1.1.0.21'] {'base_url': 'http://repo.cloud.sinocbd.com/hdp-utils/repos/centos7/', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2017-05-19 16:48:09,125 - File['/etc/yum.repos.d/HDP-UTILS.repo'] {'content': '[HDP-UTILS-1.1.0.21]\nname=HDP-UTILS-1.1.0.21\nbaseurl=http://repo.cloud.sinocbd.com/hdp-utils/repos/centos7/\n\npath=/\nenabled=1\ngpgcheck=0'}
2017-05-19 16:48:09,125 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,173 - Skipping installation of existing package unzip
2017-05-19 16:48:09,173 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,179 - Skipping installation of existing package curl
2017-05-19 16:48:09,179 - Package['hdp-select'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,184 - Skipping installation of existing package hdp-select
2017-05-19 16:48:09,279 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.0.0-1245
2017-05-19 16:48:09,281 - Checking if need to create versioned conf dir /etc/hadoop/2.5.0.0-1245/0
2017-05-19 16:48:09,282 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-05-19 16:48:09,296 - call returned (1, '/etc/hadoop/2.5.0.0-1245/0 exist already', '')
2017-05-19 16:48:09,297 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-05-19 16:48:09,311 - checked_call returned (0, '')
2017-05-19 16:48:09,311 - Ensuring that hadoop has the correct symlink structure
2017-05-19 16:48:09,311 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-05-19 16:48:09,314 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,315 - Package['wget'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,362 - Skipping installation of existing package wget
2017-05-19 16:48:09,363 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,363 - Package['tar'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,369 - Skipping installation of existing package tar
2017-05-19 16:48:09,369 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,369 - Package['asciidoc'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,375 - Skipping installation of existing package asciidoc
2017-05-19 16:48:09,375 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,376 - Package['krb5-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,381 - Skipping installation of existing package krb5-devel
2017-05-19 16:48:09,381 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,382 - Package['libxml2-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,387 - Skipping installation of existing package libxml2-devel
2017-05-19 16:48:09,388 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,388 - Package['libxslt-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,394 - Skipping installation of existing package libxslt-devel
2017-05-19 16:48:09,394 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,395 - Package['openldap-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,400 - Skipping installation of existing package openldap-devel
2017-05-19 16:48:09,400 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,401 - Package['python-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,406 - Skipping installation of existing package python-devel
2017-05-19 16:48:09,407 - Version 2.5.0.0-1245 was provided as effective cluster version.  Using package version 2_5_0_0_1245
2017-05-19 16:48:09,407 - Package['python-simplejson'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2017-05-19 16:48:09,413 - Installing package python-simplejson ('/usr/bin/yum -d 0 -e 0 -y install python-simplejson')
2017-05-19 16:48:09,731 - Execution of '/usr/bin/yum -d 0 -e 0 -y install python-simplejson' returned 1. Error: Nothing to do
2017-05-19 16:48:09,731 - Failed to install package python-simplejson. Executing '/usr/bin/yum clean metadata'
2017-05-19 16:48:09,852 - Retrying to install package python-simplejson after 30 secondsCommand failed after 1 tries

**Comment by EsharEditor** [comment]
[https://github.com/EsharEditor/ambari-hue-service/issues/15](url)

**Comment by hm631379593** [comment]
install succeed but the service cann't  start 
stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/setup_hue.py", line 45, in setup_hue
    owner = params.hue_user
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 138, in action_create
    sudo.create_file(path, content, encoding=self.resource.encoding)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 111, in create_file
    fp.write(content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 3462: ordinal not in range(128)
 stdout:
2017-05-20 23:05:34,241 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.0.0-1245
2017-05-20 23:05:34,242 - Checking if need to create versioned conf dir /etc/hadoop/2.5.0.0-1245/0
2017-05-20 23:05:34,244 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-05-20 23:05:34,258 - call returned (1, '/etc/hadoop/2.5.0.0-1245/0 exist already', '')
2017-05-20 23:05:34,259 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-05-20 23:05:34,273 - checked_call returned (0, '')
2017-05-20 23:05:34,274 - Ensuring that hadoop has the correct symlink structure
2017-05-20 23:05:34,274 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-05-20 23:05:34,361 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.0.0-1245
2017-05-20 23:05:34,363 - Checking if need to create versioned conf dir /etc/hadoop/2.5.0.0-1245/0
2017-05-20 23:05:34,364 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-05-20 23:05:34,378 - call returned (1, '/etc/hadoop/2.5.0.0-1245/0 exist already', '')
2017-05-20 23:05:34,379 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-05-20 23:05:34,393 - checked_call returned (0, '')
2017-05-20 23:05:34,393 - Ensuring that hadoop has the correct symlink structure
2017-05-20 23:05:34,393 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-05-20 23:05:34,394 - Group['hue'] {}
2017-05-20 23:05:34,395 - Group['hadoop'] {}
2017-05-20 23:05:34,395 - Group['users'] {}
2017-05-20 23:05:34,395 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,396 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,396 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-05-20 23:05:34,397 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-05-20 23:05:34,397 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,397 - User['hue'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,398 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,398 - User['hcat'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,398 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-05-20 23:05:34,399 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-05-20 23:05:34,400 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-05-20 23:05:34,403 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-05-20 23:05:34,403 - Group['hdfs'] {}
2017-05-20 23:05:34,403 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': [u'hadoop', u'hdfs']}
2017-05-20 23:05:34,403 - FS Type: 
2017-05-20 23:05:34,403 - Directory['/etc/hadoop'] {'mode': 0755}
2017-05-20 23:05:34,411 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-05-20 23:05:34,412 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-05-20 23:05:34,421 - Execute[('setenforce', '0')] {'not_if': '(! which getenforce ) || (which getenforce && getenforce | grep -q Disabled)', 'sudo': True, 'only_if': 'test -f /selinux/enforce'}
2017-05-20 23:05:34,426 - Skipping Execute[('setenforce', '0')] due to only_if
2017-05-20 23:05:34,426 - Directory['/var/log/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'hadoop', 'mode': 0775, 'cd_access': 'a'}
2017-05-20 23:05:34,427 - Directory['/var/run/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'root', 'cd_access': 'a'}
2017-05-20 23:05:34,428 - Directory['/tmp/hadoop-hdfs'] {'owner': 'hdfs', 'create_parents': True, 'cd_access': 'a'}
2017-05-20 23:05:34,430 - File['/usr/hdp/current/hadoop-client/conf/commons-logging.properties'] {'content': Template('commons-logging.properties.j2'), 'owner': 'hdfs'}
2017-05-20 23:05:34,431 - File['/usr/hdp/current/hadoop-client/conf/health_check'] {'content': Template('health_check.j2'), 'owner': 'hdfs'}
2017-05-20 23:05:34,432 - File['/usr/hdp/current/hadoop-client/conf/log4j.properties'] {'content': ..., 'owner': 'hdfs', 'group': 'hadoop', 'mode': 0644}
2017-05-20 23:05:34,438 - File['/usr/hdp/current/hadoop-client/conf/hadoop-metrics2.properties'] {'content': Template('hadoop-metrics2.properties.j2'), 'owner': 'hdfs', 'group': 'hadoop'}
2017-05-20 23:05:34,439 - File['/usr/hdp/current/hadoop-client/conf/task-log4j.properties'] {'content': StaticFile('task-log4j.properties'), 'mode': 0755}
2017-05-20 23:05:34,439 - File['/usr/hdp/current/hadoop-client/conf/configuration.xsl'] {'owner': 'hdfs', 'group': 'hadoop'}
2017-05-20 23:05:34,442 - File['/etc/hadoop/conf/topology_mappings.data'] {'owner': 'hdfs', 'content': Template('topology_mappings.data.j2'), 'only_if': 'test -d /etc/hadoop/conf', 'group': 'hadoop'}
2017-05-20 23:05:34,444 - File['/etc/hadoop/conf/topology_script.py'] {'content': StaticFile('topology_script.py'), 'only_if': 'test -d /etc/hadoop/conf', 'mode': 0755}
2017-05-20 23:05:34,582 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.0.0-1245
2017-05-20 23:05:34,583 - Checking if need to create versioned conf dir /etc/hadoop/2.5.0.0-1245/0
2017-05-20 23:05:34,584 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-05-20 23:05:34,604 - call returned (1, '/etc/hadoop/2.5.0.0-1245/0 exist already', '')
2017-05-20 23:05:34,604 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.0.0-1245', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-05-20 23:05:34,620 - checked_call returned (0, '')
2017-05-20 23:05:34,621 - Ensuring that hadoop has the correct symlink structure
2017-05-20 23:05:34,621 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-05-20 23:05:34,623 - Execute['ps -ef | grep hue | grep -v grep | awk  '{print $2}' | xargs kill -9'] {'ignore_failures': True, 'user': 'hue'}
2017-05-20 23:05:34,671 - Skipping failure of Execute['ps -ef | grep hue | grep -v grep | awk  '{print $2}' | xargs kill -9'] due to ignore_failures. Failure reason: Execution of 'ps -ef | grep hue | grep -v grep | awk  '{print $2}' | xargs kill -9' returned 137. kill: sending signal to 111769 failed: Operation not permitted
kill: sending signal to 111801 failed: No such process
kill: sending signal to 111804 failed: No such process
-bash: line 1: 111801 Done                    ps -ef
     111802                       | grep hue
     111803                       | grep -v grep
     111804                       | awk '{print $2}'
     111805 Killed                  | xargs kill -9
2017-05-20 23:05:34,671 - File['/var/run/hue/hue-server.pid'] {'owner': 'hue', 'action': ['delete']}
2017-05-20 23:05:34,671 - Deleting File['/var/run/hue/hue-server.pid']
2017-05-20 23:05:34,673 - Configure Hue Service
2017-05-20 23:05:34,673 - Directory['/var/log/hue'] {'owner': 'hue', 'create_parents': True, 'group': 'hue', 'mode': 0755, 'cd_access': 'a'}
2017-05-20 23:05:34,673 - Directory['/var/run/hue'] {'owner': 'hue', 'group': 'hue', 'create_parents': True, 'mode': 0755, 'cd_access': 'a'}
2017-05-20 23:05:34,674 - File['/var/log/hue/hue-install.log'] {'content': '', 'owner': 'hue', 'group': 'hue', 'mode': 0644}
2017-05-20 23:05:34,674 - File['/var/run/hue/hue-server.pid'] {'content': '', 'owner': 'hue', 'group': 'hue', 'mode': 0644}
2017-05-20 23:05:34,674 - Writing File['/var/run/hue/hue-server.pid'] because it doesn't exist
2017-05-20 23:05:34,674 - Changing owner for /var/run/hue/hue-server.pid from 0 to hue
2017-05-20 23:05:34,674 - Changing group for /var/run/hue/hue-server.pid from 0 to hue
2017-05-20 23:05:34,674 - Creating symlinks /usr/hdp/current/hadoop-client/lib/hue-plugins-3.11.0-SNAPSHOT.jar
2017-05-20 23:05:34,675 - Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*'] {'to': '/usr/hdp/current/hadoop-client/lib'}
2017-05-20 23:05:34,675 - Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*'] replacing old symlink to /usr/hdp/2.5.0.0-1245/hadoop/lib
2017-05-20 23:05:34,675 - Creating symbolic Link['/usr/local/hue/desktop/libs/hadoop/java-lib/*'] to /usr/hdp/current/hadoop-client/lib
2017-05-20 23:05:34,675 - Execute['find /var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package -iname "*.sh" | xargs chmod +x'] {}
2017-05-20 23:05:34,679 - HdfsResource['/user/hue'] {'security_enabled': False, 'hadoop_bin_dir': '/usr/hdp/current/hadoop-client/bin', 'keytab': [EMPTY], 'dfs_type': '', 'default_fs': 'hdfs://ambari.cloud.sinocbd.com:8020', 'user': 'hdfs', 'hdfs_resource_ignore_file': '/var/lib/ambari-agent/data/.hdfs_resource_ignore', 'hdfs_site': ..., 'kinit_path_local': 'kinit', 'principal_name': [EMPTY], 'recursive_chmod': True, 'owner': 'hue', 'hadoop_conf_dir': '/usr/hdp/current/hadoop-client/conf', 'type': 'directory', 'action': ['create_on_execute'], 'immutable_paths': [u'/apps/hive/warehouse', u'/mr-history/done', u'/app-logs', u'/tmp'], 'mode': 0755}
2017-05-20 23:05:34,680 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c 'curl -sS -L -w '"'"'%{http_code}'"'"' -X GET '"'"'http://ambari.cloud.sinocbd.com:50070/webhdfs/v1/user/hue?op=GETFILESTATUS&user.name=hdfs'"'"' 1>/tmp/tmpCyzCa6 2>/tmp/tmplxFG4g''] {'logoutput': None, 'quiet': False}
2017-05-20 23:05:34,719 - call returned (0, '')
2017-05-20 23:05:34,720 - Creating /usr/local/hue/desktop/conf/log.conf file
2017-05-20 23:05:34,722 - File['/usr/local/hue/desktop/conf/log.conf'] {'owner': 'hue', 'content': InlineTemplate(...)}
2017-05-20 23:05:34,723 - Creating /usr/local/hue/desktop/conf/pseudo-distributed.ini config file
2017-05-20 23:05:34,777 - File['/usr/local/hue/desktop/conf/pseudo-distributed.ini'] {'owner': 'hue', 'content': InlineTemplate(...)}
2017-05-20 23:05:34,777 - Writing File['/usr/local/hue/desktop/conf/pseudo-distributed.ini'] because contents don't match

Command failed after 1 tries

**Comment by EsharEditor** [comment]
Hi:
You should add a code to sudo.py file.
/usr/lib/python2.6/site-packages/resource_management/core/sudo.py
````
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by loleek** [comment]
same Consistency Check Failed
Do you have idea about how to fix this. I can't find the root cause.

**Comment by EsharEditor** [comment]
Hi loleek：
“same Consistency Check Failed”
I have fixed this bug.You should modify this configuration(  #       "replace": "password=\"???\"" --> #       "replace": "password=\"XXX\"") in pseudo-distributed.ini.

**Comment by loleek** [comment]
It works. Thank you very much.

**Comment by xfg0218** [comment]
rpm download url:  https://pkgs.org/
