### ISSUE TITLE
ambari hue service cann't start---returned 1. [ERROR] "httpfs-site" not found in server response.

### ISSUE THREAD

**Issue by luoyoumou** [EsharEditor/ambari-hue-service#23]
centos6.9 + hdp 2.6.1 +ambari Version 2.5.1.0 ( HDFS HA )

error:

/usr/lib/python2.6/site-packages/resource_management/core/environment.py:165: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  Logger.info("Skipping failure of {0} due to ignore_failures. Failure reason: {1}".format(resource, ex.message))
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 119, in locking_configure
    original_configure(obj, *args, **kw)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/setup_hue.py", line 49, in setup_hue
    add_hdfs_configuration(params.has_ranger_admin, params.security_enabled)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/common.py", line 94, in add_hdfs_configuration
    add_configurations(services_configurations)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/common.py", line 156, in add_configurations
    Execute(cmd)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 262, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 303, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/files/configs.sh set yxambari.yixia.com yxcluster httpfs-site 'httpfs.proxyuser.hue.groups' '*'' returned 1. [ERROR] "httpfs-site" not found in server response.
[ERROR] Output of `curl -k -s -u admin:yxadmin123456 "http://yxambari.yixia.com:8080/api/v1/clusters/yxcluster?fields=Clusters/desired_configs"` is:
[ERROR] { "href" : "http://yxambari.yixia.com:8080/api/v1/clusters/yxcluster?fields=Clusters/desired_configs", "Clusters" : { "cluster_name" : "yxcluster", "version" : "HDP-2.6", "desired_configs" : { "admin-log4j" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "admin-properties" : { "tag" : "version1501988174500", "user" : "admin", "version" : 10 }, "ams-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-grafana-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-grafana-ini" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-hbase-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-hbase-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-hbase-policy" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-hbase-security-site" : { "tag" : "version1502016057801", "user" : "admin", "version" : 4 }, "ams-hbase-site" : { "tag" : "version1502016057477", "user" : "admin", "version" : 4 }, "ams-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-site" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-ssl-client" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ams-ssl-server" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "atlas-tagsync-ssl" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "beeline-log4j2" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "capacity-scheduler" : { "tag" : "version1502068187846", "user" : "admin", "version" : 6 }, "cluster-env" : { "tag" : "version1502016057916", "user" : "admin", "version" : 4 }, "core-site" : { "tag" : "version1502464540735", "user" : "admin", "version" : 19 }, "dbks-site" : { "tag" : "version1502077245299", "user" : "admin", "version" : 2 }, "hadoop-env" : { "tag" : "version1502064587033", "user" : "admin", "version" : 5 }, "hadoop-metrics2.properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hadoop-policy" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hcat-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hdfs-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hdfs-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hdfs-site" : { "tag" : "version1502446142364", "user" : "admin", "version" : 8 }, "hive-atlas-application.properties" : { "tag" : "version1502016057772", "user" : "admin", "version" : 4 }, "hive-env" : { "tag" : "version1502085711698", "user" : "admin", "version" : 4 }, "hive-exec-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hive-exec-log4j2" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hive-interactive-env" : { "tag" : "version1502458946646", "user" : "admin", "version" : 4 }, "hive-interactive-site" : { "tag" : "version1502446168582", "user" : "admin", "version" : 8 }, "hive-log4j" : { "tag" : "version1502081574947", "user" : "admin", "version" : 2 }, "hive-log4j2" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hive-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hive-site" : { "tag" : "version1502085711696", "user" : "admin", "version" : 8 }, "hivemetastore-site" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hiveserver2-interactive-site" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "hiveserver2-site" : { "tag" : "version1502014500536", "user" : "admin", "version" : 2 }, "hue-auth-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-desktop-site" : { "tag" : "version1502466470898", "user" : "admin", "version" : 4 }, "hue-env" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-hadoop-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-hbase-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-hive-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-log4j-env" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-notebook-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-oozie-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-pig-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-rdbms-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-solr-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-spark-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-ugsync-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "hue-zookeeper-site" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "kerberos-env" : { "tag" : "version1502422741203", "user" : "admin", "version" : 9 }, "kms-env" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "kms-log4j" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "kms-properties" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "kms-site" : { "tag" : "version1502444450844", "user" : "admin", "version" : 4 }, "krb5-conf" : { "tag" : "version1502422741204", "user" : "admin", "version" : 9 }, "livy2-conf" : { "tag" : "version1502016057947", "user" : "admin", "version" : 4 }, "livy2-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "livy2-log4j-properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "livy2-spark-blacklist" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "llap-cli-log4j2" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "llap-daemon-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "mapred-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "mapred-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "mapred-site" : { "tag" : "version1502016057615", "user" : "admin", "version" : 4 }, "oozie-env" : { "tag" : "version1502444455719", "user" : "admin", "version" : 1 }, "oozie-log4j" : { "tag" : "version1502444455719", "user" : "admin", "version" : 1 }, "oozie-logsearch-conf" : { "tag" : "version1502444455719", "user" : "admin", "version" : 1 }, "oozie-site" : { "tag" : "version1502459031834", "user" : "admin", "version" : 3 }, "pig-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "pig-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "pig-properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "pseudo-distributed.ini" : { "tag" : "version1502466227924", "user" : "admin", "version" : 2 }, "ranger-admin-site" : { "tag" : "version1502016057630", "user" : "admin", "version" : 12 }, "ranger-env" : { "tag" : "version1502014500530", "user" : "admin", "version" : 10 }, "ranger-hdfs-audit" : { "tag" : "version1502016057833", "user" : "admin", "version" : 7 }, "ranger-hdfs-plugin-properties" : { "tag" : "version1502014500533", "user" : "admin", "version" : 3 }, "ranger-hdfs-policymgr-ssl" : { "tag" : "version1501849108055", "user" : "admin", "version" : 2 }, "ranger-hdfs-security" : { "tag" : "version1501849108054", "user" : "admin", "version" : 2 }, "ranger-hive-audit" : { "tag" : "version1502016057963", "user" : "admin", "version" : 7 }, "ranger-hive-plugin-properties" : { "tag" : "version1501849108060", "user" : "admin", "version" : 2 }, "ranger-hive-policymgr-ssl" : { "tag" : "version1501849108063", "user" : "admin", "version" : 2 }, "ranger-hive-security" : { "tag" : "version1501849108062", "user" : "admin", "version" : 2 }, "ranger-kms-audit" : { "tag" : "version1502077245283", "user" : "admin", "version" : 2 }, "ranger-kms-logsearch-conf" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "ranger-kms-policymgr-ssl" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "ranger-kms-security" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "ranger-kms-site" : { "tag" : "version1502077246900", "user" : "admin", "version" : 1 }, "ranger-logsearch-conf" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "ranger-site" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "ranger-solr-configuration" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "ranger-tagsync-policymgr-ssl" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "ranger-tagsync-site" : { "tag" : "version1502016057601", "user" : "admin", "version" : 9 }, "ranger-ugsync-site" : { "tag" : "version1502016057507", "user" : "admin", "version" : 9 }, "ranger-yarn-audit" : { "tag" : "version1502016057663", "user" : "admin", "version" : 7 }, "ranger-yarn-plugin-properties" : { "tag" : "version1502014500541", "user" : "admin", "version" : 3 }, "ranger-yarn-policymgr-ssl" : { "tag" : "version1501849108059", "user" : "admin", "version" : 2 }, "ranger-yarn-security" : { "tag" : "version1501849108058", "user" : "admin", "version" : 2 }, "slider-client" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "slider-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "slider-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark-defaults" : { "tag" : "version1502016057979", "user" : "admin", "version" : 3 }, "spark-thrift-sparkconf" : { "tag" : "version1502016057787", "user" : "admin", "version" : 3 }, "spark2-defaults" : { "tag" : "version1502016057721", "user" : "admin", "version" : 4 }, "spark2-env" : { "tag" : "version1502159640746", "user" : "admin", "version" : 2 }, "spark2-hive-site-override" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark2-log4j-properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark2-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark2-metrics-properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark2-thrift-fairscheduler" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "spark2-thrift-sparkconf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "sqoop-atlas-application.properties" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "sqoop-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "sqoop-site" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ssl-client" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "ssl-server" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "tagsync-application-properties" : { "tag" : "version1502016057492", "user" : "admin", "version" : 9 }, "tagsync-log4j" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "tez-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "tez-interactive-site" : { "tag" : "version1502178115256", "user" : "admin", "version" : 2 }, "tez-site" : { "tag" : "version1502016057677", "user" : "admin", "version" : 4 }, "usersync-log4j" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "usersync-properties" : { "tag" : "version1501986852615", "user" : "admin", "version" : 6 }, "webhcat-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "webhcat-log4j" : { "tag" : "version1502081574948", "user" : "admin", "version" : 2 }, "webhcat-site" : { "tag" : "version1502458847046", "user" : "admin", "version" : 6 }, "yarn-env" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "yarn-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "yarn-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "yarn-site" : { "tag" : "version1502085637584", "user" : "admin", "version" : 7 }, "zoo.cfg" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "zookeeper-env" : { "tag" : "version1502016057849", "user" : "admin", "version" : 4 }, "zookeeper-log4j" : { "tag" : "version1", "user" : "admin", "version" : 1 }, "zookeeper-logsearch-conf" : { "tag" : "version1", "user" : "admin", "version" : 1 } } } }
stdout:   /var/lib/ambari-agent/data/output-5823.txt

how can i slove it ? thanks

**Comment by EsharEditor** [comment]
https://github.com/EsharEditor/ambari-hue-service/issues/6

**Comment by kunxin1314** [comment]
请问你怎么解决的？能给出详细步骤吗
