### ISSUE TITLE
Install success but start failed

### ISSUE THREAD

**Issue by lil-prince** [EsharEditor/ambari-hue-service#29]
When I installed on the interface, the prompt: the installation is successful, start failure. The log is as follows:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 119, in locking_configure
    original_configure(obj, *args, **kw)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/setup_hue.py", line 27, in setup_hue
    Link("{0}/desktop/libs/hadoop/java-lib/*".format(params.hue_dir),to = "/usr/hdp/current/hadoop-client/lib")
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 238, in action_create
    sudo.symlink(self.resource.to, path)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 123, in symlink
    os.symlink(source, link_name)
OSError: [Errno 2] No such file or directory

**Comment by cherylhan** [comment]
i meet the same problem.

**Comment by tangleiNUAA** [comment]
Are you using the source instead of built package?

**Comment by jdonnelly-apixio** [comment]
Work around:
```
mkdir -p /usr/local/hue/desktop/libs/hadoop/java-lib/
chown hue:hue /usr/local/hue/desktop -R
```
