### ISSUE TITLE
centos7 + hdp 2.5 +ambari Version 2.4.2.0 waring: OSError: [Errno 2] No such file or directory. Would you like to proceed and save the changes?  how can i slove it ? thanks

### ISSUE THREAD

**Issue by cherylhan** [EsharEditor/ambari-hue-service#30]
first，I build hue3.11.0.tar and make the tar.than cp the tar to HDP baseurl/centos7/hue.
the server install ok. but it can not run.
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 28, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/hue_server.py", line 23, in configure
    setup_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/HUE/package/scripts/setup_hue.py", line 27, in setup_hue
    Link("{0}/desktop/libs/hadoop/java-lib/*".format(params.hue_dir),to = "/usr/hdp/current/hadoop-client/lib")
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 238, in action_create
    sudo.symlink(self.resource.to, path)
  File "/usr/lib/python2.6/site-packages/resource_management/core/sudo.py", line 93, in symlink
    os.symlink(source, link_name)
OSError: [Errno 2] No such file or directory

**Comment by tangleiNUAA** [comment]
Is the directory "/usr/hdp/current/hadoop-client/lib" exists?

**Comment by cherylhan** [comment]
@tangleiNUAA  yes but i dont have hue-plugins-3.11.0-SNAPSHOT.jar.is this problem？

**Comment by tangleiNUAA** [comment]
@cherylhan  The method Link("{0}/desktop/libs/hadoop/java-lib/*".format(params.hue_dir),to = "/usr/hdp/current/hadoop-client/lib") creates symlinks /usr/hdp/current/hadoop-client/lib/hue-plugins-3.11.0-SNAPSHOT.jar. Maybe your hue is not built successful. After building hue, hue-plugins-<version>-SNAPSHOT.jar will be created.

**Comment by lil-prince** [comment]
I tried to copy hue-plugins-3.11.0-SNAPSHOT.jar to / usr / hdp / current / hadoop-client / lib, but the problem still exists

**Comment by tangleiNUAA** [comment]
@lil-prince maybe you can try ln -s  to simulate the method Link(Resource).

**Comment by tangleiNUAA** [comment]
@lil-prince maybe you can try `ln -s` to simulate the method Link(Resource).

**Comment by cherylhan** [comment]
@tangleiNUAA  when i buile hue，i must install hdp？i build hue on centos7 without hdp，than copy the tar to the centos7 with hdp。when i finish the build，i make install the server is run 。i can view the web，
is there any problem ?
