### ISSUE TITLE
KeyError: u'hue'

### ISSUE THREAD

**Issue by shuiluoyukai** [EsharEditor/ambari-hue-service#38]
Hi,

I am getting the following error during installation

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 38, in <module>
    BeforeAnyHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 351, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 31, in hook
    setup_users()
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 50, in setup_users
    groups = params.user_to_groups_dict[user],
KeyError: u'hue'
Error: Error: Unable to run the custom hook script ['/usr/bin/python', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-953.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-953.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']

Any ideas how to fix it ?

thank you in advanced

**Comment by godnani2006** [comment]
I'm also facing the same issue, any solutions?

**Comment by shuiluoyukai** [comment]
ref:https://github.com/apache/ambari/pull/1453/commits/3f81ebb5ec15dbd998e29cc1b48f8e560e2ed170
vi configuration/hue-env.xml
<property>
    <name>hue_user</name>
    <value>hue</value>
    <display-name>Hue User</display-name>
    <property-type>USER</property-type>
    <description>hue user</description>
    <value-attributes>
        <type>user</type>
        <overridable>false</overridable>
        <user-groups>   //添加
            <property>
                <type>cluster-env</type>
                <name>user_group</name>
            </property>
            <property>
                <type>hue-env</type>
                <name>hue_group</name>
            </property>
        </user-groups>
    </value-attributes>
    <on-ambari-upgrade add="true"/>
</property>

**Comment by shuiluoyukai** [comment]
ref:https://github.com/apache/ambari/pull/1453/commits/3f81ebb5ec15dbd998e29cc1b48f8e560e2ed170
vi configuration/hue-env.xml
`<property>
    <name>hue_user</name>
    <value>hue</value>
    <display-name>Hue User</display-name>
    <property-type>USER</property-type>
    <description>hue user</description>
    <value-attributes>
        <type>user</type>
        <overridable>false</overridable>
        <user-groups>   //add
            <property>
                <type>cluster-env</type>
                <name>user_group</name>
            </property>
            <property>
                <type>hue-env</type>
                <name>hue_group</name>
            </property>
        </user-groups>
    </value-attributes>
    <on-ambari-upgrade add="true"/>
</property>`

**Comment by smiecj** [comment]
https://github.com/steven-matison/dfhz_hdp_mpack/pull/5/commits/bfaf5c8619710410752f926c72c929ab300be893
