### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sundaytok** [EsharEditor/ambari-hue-service#40]
when start the hue service:
stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/hue_server.py", line 76, in 
    HueServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/hue_server.py", line 14, in install
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/params.py", line 250, in 
    resourcemanager_host1 = resourcemanager_hosts[0]
IndexError: list index out of range

**Comment by TdzWork** [comment]
I'm also facing the same issue, any solutions?

**Comment by serdar-eric** [comment]
Same issue here. Any solutions?

**Comment by theforcebemay** [comment]
https://segmentfault.com/a/1190000019831315

Helped me

**Comment by qingfengtaizi** [comment]
I'm also facing the same issue, any solutions?
